version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: music_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_project
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    restart: always
    environment:
      - PYTHONPATH=/opt/airflow/src
      
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    depends_on:
      - postgres
    command: standalone

volumes:
  pgdata:
